service: XXX

custom: ${file(../../config-common.yaml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: XXX
  region: us-east-1
  profile: mos-api-sls-admin
  memorySize: 128
  timeout: 6
  deploymentBucket:
    name: mos-api-dev-lambdas
  environment:
    graphClientID: ${self:custom.graphClientID}
    graphClientSecret: ${self:custom.graphClientSecret}
    graphTenantID: ${self:custom.graphTenantID}
    mongoDbHostUnique: ${self:custom.mongoDbHostUnique}
    mongoDbPass: ${self:custom.mongoDbPass}
    mongoDbUser: ${self:custom.mongoDbUser}
    stage: ${self:provider.stage}
    upApiKey: ${self:custom.upApiKey}
    upEmployeeChangesPass: ${self:custom.upEmployeeChangesPass}
    upEmployeeChangesUser: ${self:custom.upEmployeeChangesUser}

functions:
  XXX:
    handler: Functions/XXX.XXX
    events:
      - http:
          path: XXX/XXX
          method: XXX
          cors: true
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:344440222217:layer:LayerDevNPM:1
      - arn:aws:lambda:us-east-1:344440222217:layer:LayerDevServices:1