@baseURI = https://48qoc7sqkh.execute-api.us-east-1.amazonaws.com/dev


#########
# Get all settings
GET {{baseURI}}/hubMessages/settings
Authorization: Bearer {{accessToken}}


#########
# Get all unexpired messages
GET {{baseURI}}/hubMessages/messages?expiration=unexpired
Authorization: Bearer {{accessToken}}


#########
# Get a quantity of unexpired messages
GET {{baseURI}}/hubMessages/messages?limit=4
Authorization: Bearer {{accessToken}}


#########
# Get all unexpired messages, tagged announcements
GET {{baseURI}}/hubMessages/messages?tag=announcements
Authorization: Bearer {{accessToken}}


#########
# Get 1 unexpired message, tagged announcements
GET {{baseURI}}/hubMessages/messages?expiration=unexpired&limit=1&tag=announcements
Authorization: Bearer {{accessToken}}


#########
# Add message
POST {{baseURI}}/hubMessages/addMessage
Authorization: Bearer {{accessToken}}


#########
# Update message
POST {{baseURI}}/hubMessages/updateMessage
Authorization: Bearer {{accessToken}}


#########
# Get next messageID
POST {{baseURI}}/hubMessages/nextMessageID
Authorization: Bearer {{accessToken}}