cronScheduleGSEJobSync: ${ssm:cron-schedule-gse-job-sync}
cronScheduleGSEScheduleSync: ${ssm:cron-schedule-gse-schedule-sync}
cronScheduleGSESignupSync: ${ssm:cron-schedule-gse-signup-sync}
cronScheduleGSESignupReminders: ${ssm:cron-schedule-gse-signup-reminders}
cronScheduleGSECreditReminders: ${ssm:cron-schedule-gse-credit-reminders}
cronSchedulePeopleProcessing: ${ssm:cron-schedule-people-processing}
graphClientID: ${ssm:graph-client-id}
graphClientSecret: ${ssm:graph-client-secret}
graphTenantID: ${ssm:graph-tenant-id}
mongoDbHostUnique: ${ssm:mongodb-host-unique}
devLayerARNNPM: arn:aws:lambda:us-east-1:344440222217:layer:LayerDevNPM:1
devLayerARNServices: arn:aws:lambda:us-east-1:344440222217:layer:LayerDevServices:1
mongoDbPass: ${ssm:mongodb-pass}
mongoDbUser: ${ssm:mongodb-user}
provider:
  runtime: nodejs12.x
  profile: mos-api-sls-admin
upApiKey: ${ssm:up-api-key}
upEmployeeChangesPass: ${ssm:up-emp-changes-pw}
upEmployeeChangesUser: ${ssm:up-emp-changes-user}