graphClientID: ${ssm:graph-client-id}
graphClientSecret: ${ssm:graph-client-secret}
graphTenantID: ${ssm:graph-tenant-id}
mongoDbHostUnique: ${ssm:mongodb-host-unique}
mongoDbPass: ${ssm:mongodb-pass}
mongoDbUser: ${ssm:mongodb-user}
upApiKey: ${ssm:up-api-key}
upEmployeeChangesPass: ${ssm:up-emp-changes-pw}
upEmployeeChangesUser: ${ssm:up-emp-changes-user}
servicesLayerDevARN: 